inherit_from: .rubocop_todo.yml

inherit_gem:
  test-prof: config/rubocop-rspec.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  SuggestExtensions: false
  NewCops: enable
  DisplayCopNames: true
  Exclude:
    - 'Gemfile'
    - 'bin/**/*'
    - 'db/**/*'
    - 'log/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'lib/tasks/auto_annotate_models.rake'
    - 'lib/tasks/ridgepole.rake'
    - 'config/locales/*'
    - 'config/environments/*'
    - 'config/puma.rb'
    - 'reference/**/*'

### 初期設定だと厳しいので要点だけおさえて緩めにカスタマイズ

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - staging

Metrics:
  Enabled: false

Layout/LineLength:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Enabled: false
