services:
  db:
    container_name: virtual_credit_db
    image: postgres:latest
    environment:
      POSTGRES_DB: virtual_credit_development
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  db-test:
    container_name: virtual_credit_db_test
    image: postgres:latest
    environment:
      POSTGRES_DB: virtual_credit_test
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data_test:/var/lib/postgresql/data
    ports:
      - '5433:5432'

  pgadmin:
    container_name: virtual_credit_rails_api_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: virtualcredit.official@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - db
    ports:
      - '5050:80'

  app:
    container_name: virtual_credit_rails_api_app
    build: .
    depends_on:
      - db
      - db-test
    ports:
      - '4000:4000'
    volumes:
      - .:/myapp
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 4000 -b '0.0.0.0'"
    stdin_open: true
    tty: true

  openapi:
    container_name: virtual_credit_rails_api_openapi
    image: swaggerapi/swagger-ui
    environment:
      SWAGGER_JSON: /docs/openapi.yaml
    volumes:
      - ./doc/openapi.yml:/docs/openapi.yaml
    ports:
      - '8080:8080'

  minio:
    container_name: virtual_credit_rails_api_minio
    image: minio/minio:latest
    command: ['server', '/data', '--console-address', ':9001']
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio:/data
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: password

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add myminio http://minio:9000 user password) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb myminio/virtual-credit-bucket--development;
      /usr/bin/mc policy download myminio/virtual-credit-bucket--development;
      exit 0;
      "

volumes:
  postgres_data:
  postgres_data_test:
  minio:
    driver: local
