openapi: 3.0.0
info:
  title: Virtual Credit Rails API
  version: 1.0.0
  description: OpenAPI for Virtual Credit Rails API
  contact:
    email: virtualcredit.official@gmail.com
    name: admin
servers:
  - url: 'http://localhost:4000/api'
tags:
  - name: ReleaseNote
    description: リリースノートに関するAPI
components:
  securitySchemes: {}
  schemas:
    Pagination:
      title: Pagination
      x-stoplight:
        id: n2bdaewgmjspr
      type: object
      properties:
        hasNext:
          type: boolean
          x-stoplight:
            id: d3ybcecx147m8
        hasPrevious:
          type: boolean
          x-stoplight:
            id: b6aygypylv4zf
        currentPage:
          type: integer
          x-stoplight:
            id: obdz7vxhz8o52
        totalPages:
          type: integer
          x-stoplight:
            id: oftt6zy92c0w7
        totalCount:
          type: integer
          x-stoplight:
            id: bema3583qynnb
      required:
        - hasNext
        - hasPrevious
        - currentPage
        - totalPages
        - totalCount
      x-examples: {}
    ReleaseNote:
      title: ReleaseNote
      x-stoplight:
        id: oupyewy02383q
      type: object
      properties:
        id:
          type: string
        version:
          type: string
          x-stoplight:
            id: 5rr8wkdsv8cw2
        title:
          type: string
          x-stoplight:
            id: gujhci7o78ufq
        description:
          type: string
          x-stoplight:
            id: 7f0nw7jlwgb3d
        createdAt:
          type: string
          x-stoplight:
            id: rlwyvjkwdvwmu
          format: date-time
      required:
        - id
        - version
        - title
        - description
        - createdAt
      x-examples: {}
  responses:
    ReleaseNoteIndex:
      description: リリースノート一覧
      content:
        application/json:
          schema:
            type: object
            properties:
              items:
                type: array
                items:
                  $ref: '#/components/schemas/ReleaseNote'
              meta:
                $ref: '#/components/schemas/Pagination'
            required:
              - items
              - meta
          examples:
            Example 1:
              value:
                items:
                  - id: fjh1-fu33-fk10-a85l
                    version: 1.0.0
                    title: New release
                    description: 新機能がリリースされました
                    createdAt: '2019-08-24T14:15:22Z'
                meta:
                  hasNext: true
                  hasPrevious: true
                  currentPage: 1
                  totalPages: 10
                  totalCount: 100
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                x-stoplight:
                  id: 6d68gqhean4dp
              code:
                type: integer
                x-stoplight:
                  id: 1chfxtti2vigq
              error:
                type: object
                x-stoplight:
                  id: o98zt1r4rugpg
                required:
                  - resource
                  - message
                properties:
                  resource:
                    type: string
                    x-stoplight:
                      id: pdr1a7retyfej
                  message:
                    type: string
                    x-stoplight:
                      id: ek9hn814n0t2c
            required:
              - message
              - code
              - error
          examples:
            Example 1:
              value:
                message: Request failed
                code: 400
                error:
                  resource: User
                  message: 'wrong number of arguments (given 0, expected 1)'
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                x-stoplight:
                  id: 5q40yknifnskc
              code:
                type: integer
                x-stoplight:
                  id: k19l10iq0jxjp
              error:
                type: object
                x-stoplight:
                  id: tfzeat2241crj
                required:
                  - resource
                  - message
                properties:
                  resource:
                    type: string
                    x-stoplight:
                      id: vnowom4kjdthn
                  message:
                    type: string
                    x-stoplight:
                      id: nih8cmpdiqjuu
            required:
              - message
              - code
              - error
          examples:
            Example 1:
              value:
                message: Server error
                code: 500
                error:
                  resource: User
                  message: 'undefined method `hogehoge'' for #User:0xknf83448djf1'
  examples: {}
  parameters:
    page:
      name: page
      in: query
      required: false
      schema:
        type: integer
      description: 取得したいページ数
paths:
  /v1/release_notes:
    get:
      summary: リリースノート一覧
      tags:
        - ReleaseNote
      responses:
        '200':
          $ref: '#/components/responses/ReleaseNoteIndex'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
      operationId: get-v1-release-notes
      description: リリースノートの一覧を返す
      parameters:
        - $ref: '#/components/parameters/page'
    parameters: []
