openapi: 3.0.0
info:
  title: Virtual Credit Rails API
  version: 1.0.0
  description: OpenAPI for Virtual Credit Rails API
  contact:
    email: virtualcredit.official@gmail.com
    name: admin
servers:
  - url: 'http://localhost:4000/api'
tags: []
components:
  securitySchemes: {}
paths:
  /v1/sample:
    get:
      summary: Sample
      tags: []
      responses:
        '200':
          description: OK
      operationId: get-v1-sample
      description: Sample
