name: RSpec

on: [push]

env:
  GH_TOKEN: '${{secrets.GH_TOKEN}}'

jobs:
  rspec_test:
    name: RSpec Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: password
          POSTGRES_DB: virtual_credit_rails_api_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
      - name: Install dependencies
        run: |
          sudo apt-get install libpq-dev
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Setup database
        run: bundle exec rails db:create
        env:
          RAILS_ENV: test
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: password
      - name: Database migrate
        run: bundle exec rake ridge:run RAILS_ENV='test'
      - name: Run RSpec
        run: bundle exec rspec
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: yu-yukke/virtual_credit_rails_api
