name: RuboCop

on: [push]

jobs:
  rubocop_check:
    name: RuboCop Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
      - name: Install dependencies
        run: |
          bundle install --jobs 4 --retry 3
      - name: Run RuboCop
        run: rubocop
